### ISSUE TITLE
negative mag

### ISSUE THREAD

**Issue by mpgh** [ytsapras/robonet_site#14]
Currently, we obtain negative imag values for one of the suggested targets on REA TAP
OGLE-2017-BLG-0926/MOA-2017-BLG-0313	imag -1.46

**Comment by rachel3834** [comment]
I'm not sure how to approach resolving this issue.  I've verified that the subscriber has correctly ingested the SingleModel parameters from both OB170926.model and KB170313.model files.  Looking at the TAP list now, the imag=16.74.  However, I note that while there is an ARTEMiS OB170926.align file there is no KB170313.align, which means that my code will be returning simply the unset, default values for the blending ratio for the MOA SingleModel.  

That could be causing TAP issues with the imag, because TAP calls on the most-recently-updated SingleModel to derive its values.  In this case, the timestamps of the OGLE .vs. MOA fits are as follows:

rachels-mbp-2:models rstreet$ ls -l OB170926.*
-rw-r--r--  1 rstreet  staff   46 Jun 12 13:43 OB170926.align
-rw-r--r--  1 rstreet  staff  126 Jun 12 13:43 OB170926.model
rachels-mbp-2:models rstreet$ ls -l KB170313.*
-rw-r--r--  1 rstreet  staff  91 Jun 15 08:53 KB170313.model

This will be causing TAP to receive the unset blend parameter from the MOA model. 
I think we need to add a fail-safe somewhere in the system here.  I believe Markus you added a catch within TAP to stop it picking up g=0.0 parameters, perhaps it could switch over to the OGLE model if available?
Alternatively (or perhaps as well) I could stop the subscriber from ingesting incomplete .model/.align pairs?  Or set g to an obivously-false value?

**Comment by mpgh** [comment]
It is more ibase=0 that would flag up an issue. g=0 is perfectly normal - it means the event is unblended.

**Comment by mpgh** [comment]
I am in favour of stopping the subscriber from ingesting incomplete model/align pairs.

**Comment by rachel3834** [comment]
I've looked into this, and implemented a function which could be used to prevent incomplete datasets being ingested on branch artemis_data_check.  

To clarifying how this is being handled at the DB end: the event parameters (t0,tE,u0) are stored as SingleModel objects in the DB whereas the g, ibase parameters are stored as DataFiles.  

We are checking the DB contents against both ARTEMiS' events table and the survey tables.  If I stop the ingest of .model file data because the .align is missing we would simply see event parameters (t0,tE,u0) missing from our DB event view display and wonder why, rather than seeing a clear report of an error, which could explain where the error arose from.  

Rather, I think we need to prevent the DataFile being ingested if the align file is missing.

**Comment by rachel3834** [comment]
I've deployed the updated code - the subscriber will now skip the ingest of the ARTEMiS *.dat and *.align datafiles if the align file is missing.  Markus, will this enable you to make TAP robust against this issue?

This has revealed that this issue is a relatively common one - the logs now report several events (both MOA and OGLE) for which there are no .align files.  It would be good to hear from Martin exactly why that is happening.

Of course, this does leave us with a set of events for which the DB ingested an incomplete DataFile entry previously.  I've written a management function to both find and remove those entries.  But I've not yet run it on the live DB until I hear confirmation from Markus.  

If you'd like to run the command yourself, here is how to do it within the container on Einstein:
_To see incomplete entries without editing them:_
> docker exec -i robonetsite_robonetsite_1 python /var/www/robonetsite/manage.py find_incomplete data false

_To delete incomplete entries:_
> docker exec -i robonetsite_robonetsite_1 python /var/www/robonetsite/manage.py find_incomplete data delete

**Comment by mpgh** [comment]
The current workaround is already robust in that respect (i.e. it requires align files). In the "old" 2016 system, only events with align file were processed. For OB170926 I don't see a change in the db. It is not clear to me why ARTEMiS (which has identified both datasets to belong to the same event) treated them as separate model files. I will keep the workaround active until I have tested that fully.

**Comment by rachel3834** [comment]
OK, I've run the command to remove from the DB all of the incomplete datasets that were previously ingested.

**Comment by mpgh** [comment]
We are getting closer to a consistent answer. I just don't understand why OB170926 was downgraded as far as its priority is concerned. I will keep the workaround active until I understand that. 

Based on the model files we should observe:
OGLE-2017-BLG-0926
OGLE-2017-BLG-0924
(next two rejected):
KB170305 
OB170581 

Based on the db entries:
OGLE-2017-BLG-0924
OGLE-2017-BLG-0581
OGLE-2017-BLG-0521

**Comment by ytsapras** [comment]
We should include Martin in this discussion to get some explanations.
